/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.22                          *
*        Compiled Jul  4 2013, 15:16:01                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "stm32f4xx_hal.h"
#include "DIALOG.h"
#include "GUI.h"
#include "LCDConf.h"
#include "PS2_Mouse.h" 
#include "CAN.h"
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x01)
#define ID_WINDOW_1     (GUI_ID_USER + 0x02)
#define ID_WINDOW_2     (GUI_ID_USER + 0x03)

#define ID_ICON_alarm   (GUI_ID_USER + 0x04)
#define ID_ICON_settings   (GUI_ID_USER + 0x05)
#define ID_ICON_paint   (GUI_ID_USER + 0x06)


#define ID_ICON_date   (GUI_ID_USER + 0x07)
#define ID_ICON_net   (GUI_ID_USER + 0x08)
#define ID_ICON_usb   (GUI_ID_USER + 0x09)

#define ID_ICON_alarma   (GUI_ID_USER + 0x0A)
#define ID_ICON_alarmb   (GUI_ID_USER + 0x0B)



#define ID_SLIDER_0     (GUI_ID_USER + 0xC)
#define ID_PROGBAR     	(GUI_ID_USER + 0xD)
#define ID_BUTTON_NEXT	(GUI_ID_USER + 0xE)
#define ID_BUTTON_PREV	(GUI_ID_USER + 0xF)

extern RTC_TimeTypeDef sTime;
extern RTC_DateTypeDef sDate;

extern RTC_AlarmTypeDef sAlarmA,sAlarmB;

extern GUI_PID_STATE State;
extern LTDC_HandleTypeDef hltdc;
extern RTC_HandleTypeDef hrtc;

extern GUI_CONST_STORAGE GUI_BITMAP bmalarm;
extern GUI_CONST_STORAGE GUI_BITMAP bmpaint;
extern GUI_CONST_STORAGE GUI_BITMAP bmsettings;

extern GUI_CONST_STORAGE GUI_BITMAP bmdate;
extern GUI_CONST_STORAGE GUI_BITMAP bmcan;
extern GUI_CONST_STORAGE GUI_BITMAP bmusb;
extern GUI_CONST_STORAGE GUI_BITMAP bmxp;
extern GUI_CONST_STORAGE GUI_BITMAP bmalarm_a;
extern GUI_CONST_STORAGE GUI_BITMAP bmalarm_a_d;
extern GUI_CONST_STORAGE GUI_BITMAP bmalarm_b;
extern GUI_CONST_STORAGE GUI_BITMAP bmalarm_b_d;
//extern GUI_CONST_STORAGE GUI_BITMAP bmUntitled1copy;


const GUI_BITMAP *Icons0[]={&bmalarm,&bmsettings,&bmpaint};
const GUI_BITMAP *Icons1[]={&bmdate,&bmcan,&bmusb};
const GUI_BITMAP *Icons2[]={&bmalarm_a,&bmalarm_b,&bmalarm_a_d,&bmalarm_b_d};
extern void Touch_calibration(void);
extern LCD_LayerPropTypedef          layer_prop[GUI_NUM_LAYERS];


extern PS2_MOUSE_VAR_t PS2_MOUSE_VAR;
extern uint8_t Input_Device;

extern WM_HWIN hWin_CANNetExplore;
extern WM_HWIN CANNetExplore(void);
WM_HWIN Window_0(void);
WM_HWIN Window_1(void);
WM_HWIN Layer_1(void);
PROGBAR_Handle PROGBAR_MEM;
WM_HWIN _Paint(void); 


WM_HWIN hWin_paint;

GUI_MEMDEV_Handle hMemShadow,hMemShadow1;


uint8_t Layer;

WM_HWIN hWin0,hWin1,hWin2;
extern WM_HWIN CreateTIME_DATE(void);
extern WM_HWIN CreateALARM(void);

/*********************************************************************
*
*       _cbBK
*/
/*static void _cbBK(WM_MESSAGE * pMsg) {
  int     NCode;
  int     Id;
	
  switch (pMsg->MsgId) {
	case WM_PAINT:
			GUI_Clear();
	break;	
	 default:
    WM_DefaultProc(pMsg);
    break;
  }
}*/
/*********************************************************************
*
*       _cbPaint_0
*/
static void _cbPaint_0(WM_MESSAGE * pMsg) {
  //int     NCode;
  //int     Id;
	switch (pMsg->MsgId) {
	case WM_PRE_PAINT:
		GUI_MULTIBUF_BeginEx(0);
	break;
	case WM_PAINT:
		GUI_SetBkColor(0xD0D0D0);
		GUI_Clear();
	break;
	case WM_POST_PAINT:
	GUI_MULTIBUF_EndEx(0);
	break;
	case WM_TOUCH:
	break;	
	default:
    WM_DefaultProc(pMsg);
    break;
  }
}


	
	
/*********************************************************************
*
*       _cbPaint_0
*/
static void _cbPaint_1(WM_MESSAGE * pMsg) {
  //int     NCode;
  //int     Id;
	switch (pMsg->MsgId) {
	case WM_PRE_PAINT:
		GUI_MULTIBUF_BeginEx(1);
	break;
	case WM_PAINT:
		
		GUI_SetColor(GUI_DARKBLUE);
		GUI_SetPenSize(10);
		GUI_DrawPoint(State.x,State.y);
	break;
	case WM_POST_PAINT:
	GUI_MULTIBUF_EndEx(1);
	break;
	case WM_TOUCH:
		WM_Paint(hWin_paint);
	break;	
	default:
    WM_DefaultProc(pMsg);
    break;
  }
}

WM_HWIN _Paint(void) {
	
		
	WM_CreateWindowAsChild(0,0,480,272,WM_GetDesktopWindowEx(0),WM_CF_SHOW, _cbPaint_0,0);	
	hWin_paint=WM_CreateWindowAsChild(0,0,480,272,WM_GetDesktopWindowEx(1),WM_CF_SHOW, _cbPaint_1,0);
	Layer=1;
	return hWin_paint;
		
}
	
/*********************************************************************
*
*       _cbWin_0
*/
static void _cbWin_0(WM_MESSAGE * pMsg) {
  int     NCode;
  int     Id;
	

  switch (pMsg->MsgId) {
	case WM_PID_STATE_CHANGED:
		Layer=1;
		
	break;
	case WM_PRE_PAINT:
		GUI_MULTIBUF_BeginEx(0);
	break;
	case WM_PAINT:
		GUI_DrawBitmap(&bmxp,0,0);
		//GUI_SetBkColor(GUI_LIGHTBLUE);
		//GUI_Clear();
	break;
	case WM_POST_PAINT:
		GUI_MULTIBUF_EndEx(0);
	break;
	case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICON_alarm: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
			if(!(WM_GetDialogItem(hWin0,(GUI_ID_USER + 0x0F))))
				CreateALARM();
			break;
			}
    break;
    case ID_ICON_paint: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
			WM_HideWindow(hWin0);
			WM_HideWindow(hWin2);
			GUI_SelectLayer(1);
			GUI_SetBkColor(GUI_TRANSPARENT);
			GUI_Clear();
			_Paint();
			break;
      }
    break;
    case ID_ICON_settings: 
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				WM_HideWindow(hWin0);
				WM_HideWindow(hWin2);
				Touch_calibration();	
			break;
      }
    break;
    }
  break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       _cbWin_1
*/
static void _cbWin_1(WM_MESSAGE * pMsg) {
  int     NCode;
  int     Id;
  switch (pMsg->MsgId) {
	case WM_PID_STATE_CHANGED:
		Layer=1;
		
	break;
	case WM_PRE_PAINT:
		GUI_MULTIBUF_BeginEx(0);
	break;
	case WM_PAINT:
		GUI_DrawBitmap(&bmxp,0,0);
		//GUI_SetBkColor(GUI_LIGHTBLUE);
		//GUI_Clear();
	break;
	case WM_POST_PAINT:
	GUI_MULTIBUF_EndEx(0);
	break;
	case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_ICON_date: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
			if(!(WM_GetDialogItem(hWin1,(GUI_ID_USER + 0x0F))))
				CreateTIME_DATE();
			break;
			}
    break;
    case ID_ICON_net: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
				if(hWin_CANNetExplore==0)
					CANNetExplore();
			break;
      }
    break;
    case ID_ICON_usb: 
      switch(NCode) {
      case WM_NOTIFICATION_RELEASED:
			break;
      }
    break;
    }
  break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}



/*********************************************************************
*
*       _cbLayer_1
*/
static void _cbLayer_1(WM_MESSAGE * pMsg) {
  int     NCode;
  int     Id;
	WM_HWIN hWin;
	ICONVIEW_Handle hIcon;
	int i;
	
	
  switch (pMsg->MsgId) {
		case WM_TOUCH://WM_PID_STATE_CHANGED:
		State.Layer=0;
		GUI_PID_StoreState(&State);
	break;
	case WM_PRE_PAINT:
		GUI_MULTIBUF_BeginEx(1);
	break;
	case WM_PAINT:
		
		GUI_SetBkColor(GUI_TRANSPARENT);
		GUI_Clear();
		GUI_MEMDEV_CopyToLCDAt(hMemShadow,15,0);
		GUI_MEMDEV_CopyToLCD(hMemShadow);	
		
		GUI_SetTextMode(GUI_TM_TRANS);
		GUI_SetColor(GUI_YELLOW);
		GUI_SetFont(&GUI_Font8x16);
		
		GUI_DispDecAt(sDate.Date,28,8,2);
		GUI_DispChar('.');
		GUI_DispDec(sDate.Month,2);	
		GUI_DispChar('.');
		GUI_DispDec(sDate.Year,2);
	
		GUI_DispDecAt(sTime.Hours,412,8,2);
		GUI_DispChar(':');
		GUI_DispDec(sTime.Minutes,2);
		
		
	break;
	case WM_POST_PAINT:
		GUI_MULTIBUF_EndEx(1);
	
	break;
	case WM_USER:
		WM_Paint(hWin2);
	break;	
	case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
			case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_VALUE_CHANGED:
				hWin=WM_GetDialogItem(hWin2, ID_SLIDER_0);
				i=SLIDER_GetValue(hWin);
				if(i==1)
					{
						WM_HideWindow(hWin1);
						WM_ShowWindow(hWin0);
					}
				else if(i==2)
					{	
					WM_HideWindow(hWin0);
					WM_ShowWindow(hWin1);
					}
			break;
			case WM_NOTIFICATION_RELEASED:
			break;
			}
    break;
		case ID_ICON_alarma: // Notifications sent by 'ICON_alarma'
      switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				hIcon=WM_GetDialogItem(hWin2,ID_ICON_alarma);
				WM_DeleteWindow(hIcon);
				hIcon=ICONVIEW_CreateEx(300,2,34,34,hWin2,WM_CF_SHOW|WM_CF_HASTRANS,0,(GUI_ID_USER + 0x0A),24,24);
				ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_DARKBLUE|0x80000000);
				if((RTC->CR&RTC_CR_ALRAE)==RTC_CR_ALRAE)
							{
								HAL_RTC_DeactivateAlarm(&hrtc,  RTC_ALARM_A);
								ICONVIEW_AddBitmapItem(hIcon,Icons2[2],"");
								
							}
							else
							{
								HAL_RTC_SetAlarm_IT(&hrtc,&sAlarmA,RTC_FORMAT_BIN);
								ICONVIEW_AddBitmapItem(hIcon,Icons2[0],"");
							}
			break;	
			case WM_NOTIFICATION_RELEASED:
				hWin=WM_GetDialogItem(hWin2,ID_SLIDER_0);
				WM_SetFocus(hWin);
			break;
			}
    break;
		case ID_ICON_alarmb: // Notifications sent by 'ICON_alarma'
      switch(NCode) {
			case WM_NOTIFICATION_CLICKED:
				hIcon=WM_GetDialogItem(hWin2,ID_ICON_alarmb);
				WM_DeleteWindow(hIcon);
				hIcon=ICONVIEW_CreateEx(336,2,34,34,hWin2,WM_CF_SHOW|WM_CF_HASTRANS,0,(GUI_ID_USER + 0x0B),24,24);
				ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_DARKBLUE|0x80000000);	
				if((RTC->CR&RTC_CR_ALRBE)==RTC_CR_ALRBE)
					{
						HAL_RTC_DeactivateAlarm(&hrtc,  RTC_ALARM_B);
						ICONVIEW_AddBitmapItem(hIcon,Icons2[3],"");
					}
				else
					{
						HAL_RTC_SetAlarm_IT(&hrtc,&sAlarmB,RTC_FORMAT_BIN);
						ICONVIEW_AddBitmapItem(hIcon,Icons2[1],"");
					}
			break;	
			case WM_NOTIFICATION_RELEASED:
				hWin=WM_GetDialogItem(hWin2,ID_SLIDER_0);
				WM_SetFocus(hWin);
			break;
			}
    break;			
		}
  break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}
/*********************************************************************
*
*       CreateMENU
*/

WM_HWIN Window_0(void) {
	
		uint8_t i;
		ICONVIEW_Handle hIcon;
		
		hWin0=WM_CreateWindowAsChild(0,0,480,272,WM_GetDesktopWindowEx(0),0, _cbWin_0,0);	
		for(i=0;i<3;i++)
		{
			hIcon=ICONVIEW_CreateEx(30,30+70*i,58,58,hWin0,WM_CF_SHOW|WM_CF_HASTRANS,0,(GUI_ID_USER + 0x04+i),48,48);
			ICONVIEW_AddBitmapItem(hIcon,Icons0[i],"");
			ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_RED|0xC0000000);	
		}
		return hWin0;
}

WM_HWIN Window_1(void) {
	
		uint8_t i;
		ICONVIEW_Handle hIcon;
			
		hWin1=WM_CreateWindowAsChild(0,0,480,272,WM_GetDesktopWindowEx(0),0, _cbWin_1,0);	
		for(i=0;i<3;i++)
		{
			hIcon=ICONVIEW_CreateEx(30,30+70*i,58,58,hWin1,WM_CF_SHOW|WM_CF_HASTRANS,0,(GUI_ID_USER + 0x07+i),48,48);
			ICONVIEW_AddBitmapItem(hIcon,Icons1[i],"");
			ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_RED|0xC0000000);
		}
		return hWin1;
}

WM_HWIN Layer_1(void) {
	
		uint8_t i;
		ICONVIEW_Handle hIcon;	
		SLIDER_Handle hSlider;
		
		hWin2=WM_CreateWindowAsChild(0,0,480,272,WM_GetDesktopWindowEx(1),WM_CF_SHOW, _cbLayer_1,0);
		
		PROGBAR_MEM=PROGBAR_CreateEx(0,0,15,272,hWin2,WM_CF_SHOW|WM_CF_HASTRANS,PROGBAR_CF_VERTICAL,ID_PROGBAR);
		PROGBAR_SetMinMax(PROGBAR_MEM,0,50*1024);	
		
		for(i=0;i<2;i++)
		{
			hIcon=ICONVIEW_CreateEx(300+36*i,2,34,34,hWin2,WM_CF_SHOW|WM_CF_HASTRANS,0,(GUI_ID_USER + 0x0A+i),24,24);
			ICONVIEW_AddBitmapItem(hIcon,Icons2[i],"");
			ICONVIEW_SetBkColor(hIcon, ICONVIEW_CI_SEL, GUI_DARKBLUE|0x80000000);
		}
		hSlider=SLIDER_CreateEx(190,205,120, 30,hWin2, WM_CF_SHOW|WM_CF_HASTRANS,0, ID_SLIDER_0);
		SLIDER_SetNumTicks(hSlider,2);
		SLIDER_SetRange(hSlider,1,2);
		return hWin2;
}


void MainTask(void)
{
		uint8_t i;
	GUI_MEMDEV_Handle hmem1,hmem2,hmem_L,hmem_R,hmem_T,hmem_B,hmemH,hmemV;
	
	SLIDER_SetDefaultSkin(SLIDER_SKIN_FLEX);
	PROGBAR_SetDefaultSkin(PROGBAR_SKIN_FLEX);
	FRAMEWIN_SetDefaultSkinClassic();
	FRAMEWIN_SetDefaultTextColor(0,GUI_WHITE);
	FRAMEWIN_SetDefaultTextColor(1,GUI_WHITE);
	
	EDIT_SetDefaultBkColor(EDIT_CI_ENABLED,GUI_BLACK);
	EDIT_SetDefaultFont(GUI_FONT_16B_ASCII);
		
	TEXT_SetDefaultFont(GUI_FONT_16_ASCII);
		
	//WM_EnableMemdev(1);
	WM_MULTIBUF_Enable(1);
	HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN);
	HAL_RTC_GetDate(&hrtc, &sDate, RTC_FORMAT_BIN);
	HAL_RTC_GetAlarm(&hrtc, &sAlarmA, RTC_ALARM_A,RTC_FORMAT_BIN);
	HAL_RTC_GetAlarm(&hrtc, &sAlarmB, RTC_ALARM_B,RTC_FORMAT_BIN);
	
	
	Window_0();
	Window_1();
		
	GUI_SelectLayer(1);
	
	hMemShadow=GUI_MEMDEV_CreateFixed(390,0,90,30,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hMemShadow);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	GUI_SetColor(GUI_GRAY);
	GUI_FillRect(400,10,469,19);
	
	hmem1=GUI_MEMDEV_CreateFixed(0,0,20,90,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmem1);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	GUI_DrawGradientH(0,0,20,90,GUI_TRANSPARENT,GUI_GRAY);
	
	hmem2=GUI_MEMDEV_CreateFixed(0,0,20,30,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmem2);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	GUI_DrawGradientH(0,0,20,30,GUI_TRANSPARENT,GUI_GRAY);
	
	hmemH=GUI_MEMDEV_CreateFixed(0,0,10,90,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmemH);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	
	hmemV=GUI_MEMDEV_CreateFixed(0,0,10,30,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmemV);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	
	
	hmem_L=GUI_MEMDEV_CreateFixed(0,0,10,30,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmem_L);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	hmem_R=GUI_MEMDEV_CreateFixed(0,0,10,30,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmem_R);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	hmem_T=GUI_MEMDEV_CreateFixed(0,0,90,10,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmem_T);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	hmem_B=GUI_MEMDEV_CreateFixed(0,0,90,10,GUI_MEMDEV_NOTRANS,GUI_MEMDEV_APILIST_32,GUICC_8888);
	GUI_MEMDEV_Select(hmem_B);
	GUI_SetBkColor(GUI_TRANSPARENT);
	GUI_Clear();
	
		
	GUI_MEMDEV_Select(hmemH);
	GUI_MEMDEV_DrawPerspectiveX(hmem1, 0,0,90,70,10,10);
	GUI_MEMDEV_Select(hmemV);
	GUI_MEMDEV_DrawPerspectiveX(hmem2, 0,1,28,8,10,10);
			
	GUI_MEMDEV_Rotate(hmemH,hmem_T,40,-40, -90*1000,1000);
	GUI_MEMDEV_Rotate(hmemH,hmem_B,40,-40, 90*1000,1000);
	GUI_MEMDEV_Rotate(hmemV,hmem_R,0,0,180*1000,1000);
	
	GUI_MEMDEV_Select(hMemShadow);
	GUI_MEMDEV_WriteAt(hmem_T, 390, 0);
	GUI_MEMDEV_WriteAt(hmem_B, 390, 20);
	GUI_MEMDEV_WriteAt(hmemV, 390, 0);
	GUI_MEMDEV_WriteAt(hmem_R, 470, 0);
	
	GUI_MEMDEV_Select(0);
	
	GUI_MEMDEV_Delete(hmem1);
	GUI_MEMDEV_Delete(hmem2);
	GUI_MEMDEV_Delete(hmem_L);
	GUI_MEMDEV_Delete(hmem_R);
	GUI_MEMDEV_Delete(hmem_T);
	GUI_MEMDEV_Delete(hmem_B);
	GUI_MEMDEV_Delete(hmemH);
	GUI_MEMDEV_Delete(hmemV);
	
	Layer_1();
	//WM_ShowWindow(hWin1);	
	WM_ShowWindow(hWin0);
	//
	if(Input_Device==1)
	{GUI_CURSOR_Show();
		Layer=1;
		State.y=136;
		State.x=240;
		//GUI_MOUSE_StoreState(&State);
		//GUI_CURSOR_SetPosition(State.x,State.y);
	}
	
	for(i=20;i<70;i++)
		{
			TIM13->CCR1=i;
			GUI_Delay(50);
		}
		
while(1)	
{			
			State.Layer=Layer;
		//GUI_TOUCH_StoreStateEx(&State);	
			//GUI_MOUSE_StoreState(&State);
			//if(Input_Device==INPUT_DEV_MOUSE)
			//{
				//GUI_MOUSE_GetState(&State);
				//GUI_CURSOR_SetPosition(State.x,State.y);
			//}
			//else
			//	GUI_TOUCH_StoreStateEx(&State);
			
			GUI_Delay(10);
	}

}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
